name: brekete_connect
description: Brekete Family Connect App.

version: 1.1.2+30

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  chewie: ^1.2.2
  cloud_firestore: ^2.4.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  firebase_storage: ^10.0.1
  flutter:
    sdk: flutter
  flutter_facebook_login: ^3.0.0
  flutter_inappwebview: ^5.3.2
  flutter_rating_bar: ^1.1.0
  flutter_spinkit: ^4.1.2+1
  fluttertoast: ^8.0.8
  google_sign_in: ^5.0.7
  image_picker: ^0.8.2
  modal_progress_hud: ^0.1.3
  path_provider: ^2.0.2
  permission_handler: ^9.2.0
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  table_calendar: ^2.1.0
  url_launcher: ^6.0.9
  video_player: ^2.1.14
  webview_flutter: ^2.0.9
  cached_network_image: ^3.2.0
  badges: ^2.0.2
  timeago: ^3.1.0
  carousel_slider: ^4.0.0
  open_file: ^3.2.1
  flowder: ^0.2.0
  #percent_indicator: ^4.2.1
  percent_indicator: ^3.4.0
  font_awesome_flutter: ^9.2.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/appIcon.jpeg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - images/
  #  - images/a_dot_ham.jpeg
 